{% set version = '0.7.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.tree
  version: {{ version|replace("-", "_") }}

source:
  fn: data.tree_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/data.tree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/data.tree/data.tree_{{ version }}.tar.gz
  sha256: 0b326682946ae60780329f34725a05a343b631964df0a66a14c9367060685b17

build:
  merge_build_host: True  # [win]
  number: 0
  # no r-diagrammer win packages
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-diagrammer >=1.0.0
    - r-r6
    - r-stringr
  run:
    - r-base
    - r-diagrammer >=1.0.0
    - r-r6
    - r-stringr

test:
  commands:
    - $R -e "library('data.tree')"           # [not win]
    - "\"%R%\" -e \"library('data.tree')\""  # [win]

about:
  home: http://github.com/gluc/data.tree
  license: GPL (>= 2)
  summary: Create tree structures from hierarchical data, and traverse the tree in various orders.
    Aggregate, cumulate, print, plot, convert to and from data.frame and more. Useful
    for decision trees, machine learning, finance, conversion from and to JSON, and
    many other applications.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
