{% set version = "0.7.8" %}

package:
  name: r-data.tree
  version: {{ version }}

source:
  fn: data.tree_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/data.tree_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/data.tree/data.tree_{{ version }}.tar.gz
  sha256: 0b326682946ae60780329f34725a05a343b631964df0a66a14c9367060685b17

build:
  number: 0
  # slipping Windows b/c we are missing: r-diagrammer -> r-igraph
  skip: True  # [win]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-diagrammer >=1.0.0
    - r-r6
    - r-stringr
  run:
    - r-base
    - r-diagrammer >=1.0.0
    - r-r6
    - r-stringr

test:
  commands:
    - $R -e "library('data.tree')"  # [not win]
    - "\"%R%\" -e \"library('data.tree')\""  # [win]

about:
  home: https://github.com/tidyverse/data.tree
  license: GPL (>= 2)
  summary: Create tree structures from hierarchical data, and traverse the tree in various orders.
    Aggregate, cumulate, print, plot, convert to and from data.frame and more. Useful
    for decision trees, machine learning, finance, conversion from and to JSON, and
    many other applications.

extra:
  recipe-maintainers:
    - ocefpaf
