travis:
  secure:
    BINSTAR_TOKEN: nmcKoqz0Tamp5NBhjLjDNpdEpDfv/jtuIKeda2vp4OdSGs7bBs30+ppdPbZUeo++1osjmQszHaQ+Amy7WkBZqJC31lK0d5CgJ4uPi24wY82FMl5/8RP1O//F1EI6KYyjB2gJnj3nSQqUksXuP28bF1Rw/65uwear9YanCIX84KD7HuDoAPKCwRRvRxTTC+8LwGsGg3+o5UuFEd3KAiVSGPxdBQ9nTUSGqukOfsClh8qv8A5YtKNXXRu1VeG7eeSlC8SMKILXs9/mHp28ppD0ZVS4abR/aQ5OwEgu6VYd89sQWpdk2tDz8U/vKQhyuAf63NwOCwe4PXZkzufc9W8okfsy+tp2Aa7IuSbmWTa69oWnztuOTe7L/kPyuKeYjps2/9oSVyQmWpcytfpZ+JpCxEJH56f6Md8g8PHXFF1RRMIaUDfDroWnwnF8DXN6uZPCmQkCDpCsVpKf0IVdB8J4x2iljRZjh5ET3Z78TyX0BvWVQCP4MrV17StqE7V7LpfVfuqdFNDPJtT4oUPxc3Lzc3Ki+krIAF55Pr3D9Y0I1LT1KcDaUy6uNyNZfBZySL1QzSG3ruasd1ioi70Rum8y3Y43OZ+TSdy7eyRX88gGG42zHmafOI9BFb9lhb4CxSsDqK5e7uK+D+G/7BicJ2lm17hssQb/m5Sy97iQsYaLrdU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
