appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EfUVSRbOvw8y+fqTPHvc4Lgb8u/F+i7stiKkmUMYaCsQN0aqtwnN1W5HwLx4QBg9KM+FjSnvfAhZc7m+jbvSyHCggfWfQzHOuQVOqFDGUJra3qQOi0FEHIYEYatuixBozSoQwp/UxAVK5SIxiamo2NaXyLX1czSOeMMwh6H3oLikNudFXBJH1rE0vjn6rBPOTHlsJlRh4qyS+kIgqI3iVxko5weMjSwfLHnk7rqYJAbd2qRG0JQaBcBKGRXZ72QzmV1yITW6VNmiDWmG/YbNwph/foVP+bJMU+D67u1jlPORTS/Fjnn0Q5Zxk6CvrijU1bA+ziIyyaH8lWCJvUj3YB4IfFGWMidWY7MHMiO7tk3DIqxRorClQx2D2lOujaXNMXIv55PtsCNNxUj4LLo6CGSbCsKS64FHGsvTnvSy3ZK1EevFEhvg8KT6J3+ZJdn8g03rZ5wHShA3aD9NeYEMWaee+jiFq4csbRMFxnkZ4sKFJ0pJvCWaC7I7r8hvQt9oak1Ou2P3oNzy78WXd+5t9F1HdcMMpHrU0s+p4ziG/NeMyOdhB1brXN6PaOt4zXz9qq6diSFhM9PROsjZWyhArTFXuoND4t1pZPRcE6bFVrwu6VHS4ox5IRu+CG/qRnPQEnPk3s+0wqvqXJ7qskqYqrIMJ+c5Xl8ZL6dmWMzQVng=
